### ISSUE TITLE
jaxtyping requirement

### ISSUE THREAD

**Issue by maturk** [hangg7/nerfview#1]
Hi, 

I am wondering why the `jaxtyping==0.2.29` requirement, could it be lowered? I am running python 3.8 and seems that this is not supported. Nerfstudio has ` jaxtyping>=0.2.15` requirement. 

Thanks.

**Comment by hangg-sai** [comment]
Thanks for the suggestion, that makes sense.

**Comment by hangg7** [comment]
It makes sense, fixed in https://github.com/hangg7/nerfview/commit/39896163efb0e48fabfb1a8f6672268551cae521 and bumped up to 0.0.3. Feel free to try it out by `pip install nerfview==0.0.3`
