### ISSUE TITLE
How init the viewer from a given camera pose?

### ISSUE THREAD

**Issue by littlepure2333** [hangg7/nerfview#5]
Hi thanks for your wonderful project. But how to initiate the viewer from a given camera pose?

**Comment by brentyi** [comment]
This is an imperfect solution but one option that should currently work:
```python
server = viser.ViserServer()

@server.on_client_connect
def _(client: viser.ClientHandle) -> None:
    client.camera.position = (1., 1., 1.)
    client.camera.look_at = (0., 0., 0.)
```

There's a full list of supported properties here: https://viser.studio/latest/camera_handles/

related: https://github.com/nerfstudio-project/viser/issues/259

**Comment by littlepure2333** [comment]
Thanks for your prompt reply. Helps a lot!
